repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent", "2", "--no-sort-keys"]

  - repo: local
    hooks:
      - id: ipf-validate
        name: IPF schema validate
        entry: python validation/validate.py --schema schema/ipf-schema-v1.0.json catalog examples
        language: system
        pass_filenames: false
